<a href="https://colab.research.google.com/github/aryanibos/Information-Retrival/blob/main/P2_Information_Retrival.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)

In [2]:
import nltk # mengimpor pustaka
from nltk.corpus import stopwords # mengimpor modul
from nltk.tokenize import word_tokenize # mengimpor fungsi
import numpy as np #mengimpor pustaka
import pandas as pd #manipulasi data
import re # mencari dan mencocokan string
import math #menggunakan berbagai fungsi dan konstatanta secara matematika
from tqdm import tqdm #visualisasi untuk mengetahui proses running

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
stop_words= set(stopwords.words('indonesian'))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

https://drive.google.com/file/d/1ysv88LcYDyjYrSrC_Fke4JThiv2BuP9y/view?usp=drive_link

In [3]:
!pip install gdown

import gdown
file_id = "1ysv88LcYDyjYrSrC_Fke4JThiv2BuP9y"
url = f"https://drive.google.com/uc?id={file_id}"

gdown.download(url, "data.xml", quiet=False)

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.20.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2025.11.12)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

Downloading...
From (original): https://drive.google.com/uc?id=1ysv88LcYDyjYrSrC_Fke4JThiv2BuP9y
From (redirected): https://drive.google.com/uc?id=1ysv88LcYDyjYrSrC_Fke4JThiv2BuP9y&confirm=t&uuid=f13aa8e6-26d4-444f-a5e1-52a53641dee8
To: /content/data.xml
100%|██████████| 2.56M/2.56M [00:00<00:00, 46.9MB/s]

'data.xml'

In [4]:
df = pd.read_xml('data.xml')
df.drop(columns = ['sumber', 'tanggal', 'link'], inplace=True)
df.head()

,id,kategori,judul,isi,jumlahkata
0,1,Teknologi,"Ponsel Huawei Honor 4C Dibanderol Rp 2,2 Juta","JAKARTA, KOMPAS.com Ponsel Android Huawei Hon...",315
1,2,Teknologi,Asosiasi: RPP E-commerce Tidak Sesuai Hasil Di...,"JAKARTA, KOMPAS.com - Sejak 2013, wacana tenta...",419
2,3,Teknologi,"Pemesan ""iPhone Jadi Sabun"" Karyawan Pesaing L...","JAKARTA, KOMPAS.com Danis Darusman, pelanggan ...",265
3,4,Teknologi,"""Autofeather Failure"", Momok bagi Pesawat Bali...",KOMPAS.com Salah satu momok yang dihadapi dala...,481
4,5,Teknologi,Laptop Bezel Tertipis di Dunia Masuk Indonesia,"JAKARTA, KOMPAS.com - Resmi diperkenalkan pada...",227

In [5]:
df['kategori'].unique()

array(['Teknologi', 'Bisnis Ekonomi', 'Nasional', 'Olahraga', 'Travel',
       'Bola', 'Otomotif', 'Lifestyle'], dtype=object)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1502 entries, 0 to 1501
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1502 non-null   int64
 1   kategori    1502 non-null   object
 2   judul       1502 non-null   object
 3   isi         1502 non-null   object
 4   jumlahkata  1502 non-null   int64
dtypes: int64(2), object(3)
memory usage: 58.8+ KB

In [7]:
df.isnull().sum()

id            0
kategori      0
judul         0
isi           0
jumlahkata    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
def caseFolding(text):
    text = text.lower()
    return text

contoh = "Terima kasih, Kak! Kamu sangat baik sekali kepadaku hari ini."
print(f"original : {contoh}")
print(f"case folded : {caseFolding(contoh)}")

original : Terima kasih, Kak! Kamu sangat baik sekali kepadaku hari ini.
case folded : terima kasih, kak! kamu sangat baik sekali kepadaku hari ini.

In [10]:
def punctuationRemoval(text):
    text = re.sub(r'[^\w\s]', ' ', text)
    return text

contoh = "Terima kasih, Kak! Kamu sangat baik sekali kepadaku hari ini."
print(f"original : {contoh}")
print(f"punctuation removed : {punctuationRemoval(contoh)}")

original : Terima kasih, Kak! Kamu sangat baik sekali kepadaku hari ini.
punctuation removed : Terima kasih  Kak  Kamu sangat baik sekali kepadaku hari ini

In [11]:
def remove_stopwords(text):
    tokens = text.split()          # memecah teks menjadi kata-kata
    filtered = []                  # menyiapkan list kosong untuk menampung kata yang lolos

    # Loop setiap kata
    for word in tokens:
        if word not in stop_words: # Kalau kata bukan stopword
            filtered.append(word)  # Tambahkan ke list filtered

    # Menggabungkan kembali kata-kata menjadi kalimat
    cleaned_text = " ".join(filtered)
    return cleaned_text

contoh_teks = "saya adalah Mahasiswa STT Terpadu Nurul Fikri"

print("Teks asli        :", contoh_teks)
print("Setelah proses   :", remove_stopwords(contoh_teks))

Teks asli        : saya adalah Mahasiswa STT Terpadu Nurul Fikri
Setelah proses   : Mahasiswa STT Terpadu Nurul Fikri

In [12]:
df['clean'] = df['isi'].apply(caseFolding)
df['clean'] = df['clean'].apply(punctuationRemoval)
df['clean'] = df['clean'].apply(remove_stopwords)

df.head()

,id,kategori,judul,isi,jumlahkata,clean
0,1,Teknologi,"Ponsel Huawei Honor 4C Dibanderol Rp 2,2 Juta","JAKARTA, KOMPAS.com Ponsel Android Huawei Hon...",315,jakarta kompas com ponsel android huawei honor...
1,2,Teknologi,Asosiasi: RPP E-commerce Tidak Sesuai Hasil Di...,"JAKARTA, KOMPAS.com - Sejak 2013, wacana tenta...",419,jakarta kompas com 2013 wacana rancangan perat...
2,3,Teknologi,"Pemesan ""iPhone Jadi Sabun"" Karyawan Pesaing L...","JAKARTA, KOMPAS.com Danis Darusman, pelanggan ...",265,jakarta kompas com danis darusman pelanggan la...
3,4,Teknologi,"""Autofeather Failure"", Momok bagi Pesawat Bali...",KOMPAS.com Salah satu momok yang dihadapi dala...,481,kompas com salah momok dihadapi pesawat turbop...
4,5,Teknologi,Laptop Bezel Tertipis di Dunia Masuk Indonesia,"JAKARTA, KOMPAS.com - Resmi diperkenalkan pada...",227,jakarta kompas com resmi diperkenalkan ajang c...

In [13]:
import nltk  # Mengimpor pustaka NLTK untuk pemrosesan bahasa alami
from nltk.corpus import stopwords  # Mengimpor modul stopwords dari NLTK untuk mengakses kata umum
from nltk.tokenize import word_tokenize  # Mengimpor fungsi untuk memecah teks menjadi kata

import numpy as np  # Mengimpor pustaka numpy untuk perhitungan numerik
import pandas as pd  # Memanipulasi data dalam bentuk tabel

import re  # Mencari dan mencocokkan string dengan pola teks (Regex)
import math  # Menggunakan berbagai fungsi matematika
from tqdm import tqdm  # Visualisasi progress bar saat proses berjalan

nltk.download('punkt')        # Mengunduh data untuk tokenisasi kalimat dan kata
nltk.download('stopwords')    # Mengunduh daftar stopwords untuk bahasa Inggris & lainnya
nltk.download('punkt_tab')    # Mengunduh data tokenisasi tambahan yang dibutuhkan NLTK

stop_words = set(stopwords.words('indonesian'))  # Menyimpan daftar stopwords Indonesia dalam bentuk set

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [14]:
def compute_word_frequency(text):
    words = word_tokenize(text)   # Melakukan tokenisasi teks menjadi kata
    frequency_table = {}          # Dictionary untuk menyimpan kata + frekuensinya

    # Iterasi setiap kata dalam list words
    for word in words:
        if word in frequency_table:       # Jika kata sudah ada, tambahkan hitungannya
            frequency_table[word] += 1
        else:
            frequency_table[word] = 1      # Jika kata belum ada, buat baru

    return frequency_table

In [15]:
df['word_frequency'] = df['clean'].apply(compute_word_frequency)
df.head()

,id,kategori,judul,isi,jumlahkata,clean,word_frequency
0,1,Teknologi,"Ponsel Huawei Honor 4C Dibanderol Rp 2,2 Juta","JAKARTA, KOMPAS.com Ponsel Android Huawei Hon...",315,jakarta kompas com ponsel android huawei honor...,"{'jakarta': 2, 'kompas': 1, 'com': 1, 'ponsel'..."
1,2,Teknologi,Asosiasi: RPP E-commerce Tidak Sesuai Hasil Di...,"JAKARTA, KOMPAS.com - Sejak 2013, wacana tenta...",419,jakarta kompas com 2013 wacana rancangan perat...,"{'jakarta': 2, 'kompas': 1, 'com': 1, '2013': ..."
2,3,Teknologi,"Pemesan ""iPhone Jadi Sabun"" Karyawan Pesaing L...","JAKARTA, KOMPAS.com Danis Darusman, pelanggan ...",265,jakarta kompas com danis darusman pelanggan la...,"{'jakarta': 1, 'kompas': 1, 'com': 1, 'danis':..."
3,4,Teknologi,"""Autofeather Failure"", Momok bagi Pesawat Bali...",KOMPAS.com Salah satu momok yang dihadapi dala...,481,kompas com salah momok dihadapi pesawat turbop...,"{'kompas': 1, 'com': 1, 'salah': 2, 'momok': 1..."
4,5,Teknologi,Laptop Bezel Tertipis di Dunia Masuk Indonesia,"JAKARTA, KOMPAS.com - Resmi diperkenalkan pada...",227,jakarta kompas com resmi diperkenalkan ajang c...,"{'jakarta': 2, 'kompas': 1, 'com': 1, 'resmi':..."

In [16]:
N = len(df)

document_frequencies = {}

for word_freq in df['word_frequency']:
    for word in word_freq.keys():
        if word in document_frequencies:
            document_frequencies[word] += 1
        else:
            document_frequencies[word] = 1

idf = {}

for word, df_t in document_frequencies.items():
    idf[word] = math.log((1 + N) / (1 + df_t))

list(idf.items())[:10]

[('jakarta', 0.7741883905630713),
 ('kompas', 2.2653623825034375),
 ('com', 0.9166234552177669),
 ('ponsel', 4.179724173823825),
 ('android', 5.012633296758929),
 ('huawei', 5.523458920524919),
 ('honor', 5.705780477318874),
 ('4c', 5.928924028633084),
 ('resmi', 2.503034034380557),
 ('meluncur', 4.830311739964974)]

In [17]:
# Menghitung TF-IDF untuk setiap dokumen
def compute_tf_idf(word_freq, idf_dict):
    tf_idf = {}

    for word, tf in word_freq.items():
        if word in idf_dict:
            tf_idf[word] = tf * idf_dict[word]   # Rumus: TF * IDF

    return tf_idf

tf_idf_list = []

for freq in df['word_frequency']:
    tf_idf_value = compute_tf_idf(freq, idf)
    tf_idf_list.append(tf_idf_value)

df['tf_idf'] = tf_idf_list
df.head()

,id,kategori,judul,isi,jumlahkata,clean,word_frequency,tf_idf
0,1,Teknologi,"Ponsel Huawei Honor 4C Dibanderol Rp 2,2 Juta","JAKARTA, KOMPAS.com Ponsel Android Huawei Hon...",315,jakarta kompas com ponsel android huawei honor...,"{'jakarta': 2, 'kompas': 1, 'com': 1, 'ponsel'...","{'jakarta': 1.5483767811261426, 'kompas': 2.26..."
1,2,Teknologi,Asosiasi: RPP E-commerce Tidak Sesuai Hasil Di...,"JAKARTA, KOMPAS.com - Sejak 2013, wacana tenta...",419,jakarta kompas com 2013 wacana rancangan perat...,"{'jakarta': 2, 'kompas': 1, 'com': 1, '2013': ...","{'jakarta': 1.5483767811261426, 'kompas': 2.26..."
2,3,Teknologi,"Pemesan ""iPhone Jadi Sabun"" Karyawan Pesaing L...","JAKARTA, KOMPAS.com Danis Darusman, pelanggan ...",265,jakarta kompas com danis darusman pelanggan la...,"{'jakarta': 1, 'kompas': 1, 'com': 1, 'danis':...","{'jakarta': 0.7741883905630713, 'kompas': 2.26..."
3,4,Teknologi,"""Autofeather Failure"", Momok bagi Pesawat Bali...",KOMPAS.com Salah satu momok yang dihadapi dala...,481,kompas com salah momok dihadapi pesawat turbop...,"{'kompas': 1, 'com': 1, 'salah': 2, 'momok': 1...","{'kompas': 2.2653623825034375, 'com': 0.916623..."
4,5,Teknologi,Laptop Bezel Tertipis di Dunia Masuk Indonesia,"JAKARTA, KOMPAS.com - Resmi diperkenalkan pada...",227,jakarta kompas com resmi diperkenalkan ajang c...,"{'jakarta': 2, 'kompas': 1, 'com': 1, 'resmi':...","{'jakarta': 1.5483767811261426, 'kompas': 2.26..."

In [18]:
# Pilih dokumen berdasarkan id berita
id_berita = 1   # ubah sesuai id berita yang ingin ditampilkan
row = df[df['id'] == id_berita].iloc[0]

# Ambil data TF dan TF-IDF dari dokumen tersebut
tf_data    = row['word_frequency']
tfidf_data = row['tf_idf']

rows = []
for term, tf in tf_data.items():
    idf_value   = idf.get(term, 0)
    tfidf_value = tfidf_data.get(term, 0)

    rows.append({
        'term':  term,
        'tf':    tf,
        'idf':   round(idf_value, 4),
        'tfidf': round(tfidf_value, 4)
    })

# Buat DataFrame detail TF-IDF
df_tfidf_detail = pd.DataFrame(rows)

# Mengurutkan dari nilai tfidf terbesar
df_tfidf_detail = df_tfidf_detail.sort_values(by='tfidf', ascending=False)

print(f"Hasil TF-IDF untuk id berita = {id_berita}\n")
print(df_tfidf_detail.to_string(index=False))

Hasil TF-IDF untuk id berita = 1

          term  tf    idf   tfidf
         honor   6 5.7058 34.2347
            4c   5 5.9289 29.6446
        huawei   5 5.5235 27.6173
        ponsel   6 4.1797 25.0783
        darren   3 6.6221 19.8662
         ultra   3 5.7058 17.1173
      prosesor   3 4.7503 14.2508
  merancangnya   2 6.6221 13.2441
         photo   2 6.2166 12.4332
          foto   3 3.9830 11.9490
      snapshot   2 5.9289 11.8578
    megapiksel   2 5.9289 11.8578
  penjualannya   2 5.9289 11.8578
       refocus   2 5.9289 11.8578
         audio   2 5.7058 11.4116
          fast   2 5.7058 11.4116
      pengguna   3 3.7599 11.2796
        selfie   2 5.5235 11.0469
            gb   2 5.5235 11.0469
          mode   2 5.3693 10.7386
      memotret   2 5.2358 10.4716
             2   5 2.0525 10.2626
       android   2 5.0126 10.0253
             4   4 2.2276  8.9105
        kamera   2 4.3708  8.7416
         fitur   2 3.9479  7.8958
        online   2 3.7889  7.5777
         fixed   1 6.6221  6.6221
         kirin   1 6.6221  6.6221
     hisilicon   1 6.6221  6.6221
   pembuatanya   1 6.6221  6.6221
       compass   1 6.6221  6.6221
       ambient   1 6.6221  6.6221
     proximity   1 6.6221  6.6221
 accelerometer   1 6.6221  6.6221
           802   1 6.6221  6.6221
          dual   1 6.6221  6.6221
      seteajam   1 6.6221  6.6221
     ketajaman   1 6.6221  6.6221
     konduktor   1 6.6221  6.6221
   menyelipkan   1 6.6221  6.6221
    department   1 6.6221  6.6221
        retail   1 6.6221  6.6221
      datasrip   1 6.6221  6.6221
           usb   1 6.6221  6.6221
           lag   1 6.2166  6.2166
           rom   1 6.2166  6.2166
         light   1 6.2166  6.2166
          wide   1 6.2166  6.2166
           550   1 6.2166  6.2166
          wifi   1 6.2166  6.2166
          semi   1 6.2166  6.2166
           gsm   1 6.2166  6.2166
        kitkat   1 6.2166  6.2166
      lollipop   1 6.2166  6.2166
         focus   1 6.2166  6.2166
           sim   1 6.2166  6.2166
             0   2 3.0811  6.1622
          octa   1 5.9289  5.9289
        beauty   1 5.9289  5.9289
       offline   1 5.9289  5.9289
            3g   1 5.9289  5.9289
mendapatkannya   1 5.9289  5.9289
          sony   1 5.9289  5.9289
           620   1 5.9289  5.9289
  berkecepatan   1 5.9289  5.9289
  mengabadikan   1 5.9289  5.9289
        device   1 5.9289  5.9289
          inci   1 5.7058  5.7058
   menyematkan   1 5.7058  5.7058
   penyimpanan   1 5.7058  5.7058
           ghz   1 5.7058  5.7058
         smart   1 5.7058  5.7058
       pungkas   1 5.7058  5.7058
    membelinya   1 5.7058  5.7058
         sales   1 5.5235  5.5235
           lte   1 5.3693  5.3693
         mulus   1 5.3693  5.3693
            4g   1 5.3693  5.3693
          game   1 5.3693  5.3693
          core   1 5.3693  5.3693
     bluetooth   1 5.3693  5.3693
    perusahaan   2 2.6708  5.3417
        sistem   2 2.6708  5.3417
           mah   1 5.2358  5.2358
         klaim   1 5.2358  5.2358
             n   1 5.2358  5.2358
           ram   1 5.2358  5.2358
         objek   1 5.1180  5.1180
     mengakses   1 5.1180  5.1180
        sensor   1 5.1180  5.1180
       digital   1 5.1180  5.1180
      banderol   1 5.1180  5.1180
     berdurasi   1 5.1180  5.1180
     berfungsi   1 5.1180  5.1180
  konektivitas   1 5.1180  5.1180
         lebar   1 5.0126  5.0126
    distribusi   1 5.0126  5.0126
         detik   1 5.0126  5.0126
      dibekali   1 5.0126  5.0126
     berukuran   1 4.9173  4.9173
        memori   1 4.9173  4.9173
      utamanya   1 4.8303  4.8303
      meluncur   1 4.8303  4.8303
        cantik   1 4.7503  4.7503
   spesifikasi   1 4.7503  4.7503
  berkapasitas   1 4.6762  4.6762
      didukung   1 4.6072  4.6072
       baterai   1 4.6072  4.6072
        gambar   1 4.5426  4.5426
       rekaman   1 4.5426  4.5426
        urusan   1 4.4820  4.4820
      aplikasi   1 4.4820  4.4820
        unggul   1 4.4820  4.4820
      tiongkok   1 4.4820  4.4820
             g   1 4.4820  4.4820
       diklaim   1 4.4248  4.4248
    peluncuran   1 4.3195  4.3195
      jaringan   1 4.3195  4.3195
             5   2 2.1391  4.2781
      menengah   1 4.2707  4.2707
      bergerak   1 4.2242  4.2242
          toko   1 4.2242  4.2242
     sayangnya   1 4.1797  4.1797
       dipakai   1 4.1797  4.1797
      mengatur   1 4.1372  4.1372
     september   1 4.0571  4.0571
          usia   1 4.0194  4.0194
         suara   1 3.9140  3.9140
         kelas   1 3.9140  3.9140
          area   1 3.8812  3.8812
       menjual   1 3.8495  3.8495
     penjualan   1 3.8187  3.8187
       operasi   1 3.7889  3.7889
       manager   1 3.7889  3.7889
           nya   1 3.7043  3.7043
     dibanding   1 3.7043  3.7043
             b   1 3.6517  3.6517
         fokus   1 3.6263  3.6263
        buatan   1 3.5310  3.5310
       kinerja   1 3.4866  3.4866
       agustus   1 3.4651  3.4651
      tambahan   1 3.4651  3.4651
            35   1 3.3262  3.3262
            13   1 3.0525  3.0525
            18   1 3.0386  3.0386
         pasar   1 2.9458  2.9458
     mendukung   1 2.9458  2.9458
             8   1 2.7826  2.7826
     indonesia   2 1.3856  2.7713
         media   1 2.7509  2.7509
            11   1 2.6902  2.6902
            rp   1 2.6518  2.6518
         harga   1 2.6147  2.6147
         hasil   1 2.5703  2.5703
            pt   1 2.5445  2.5445
       bermain   1 2.5361  2.5361
         resmi   1 2.5030  2.5030
          juta   1 2.3385  2.3385
            10   1 2.2979  2.2979
        kompas   1 2.2654  2.2654
         milik   1 2.1167  2.1167
             3   1 2.1003  2.1003
       jakarta   2 0.7742  1.5484
          juli   1 1.4017  1.4017
             1   2 0.5387  1.0774
             7   1 1.0769  1.0769
           com   1 0.9166  0.9166
            id   1 0.7415  0.7415
          rabu   1 0.6521  0.6521
          2015   1 0.6035  0.6035
            co   1 0.4996  0.4996

In [20]:
# Mengumpulkan kata dalam setiap dokumen
all_terms_set = set()    # Menyimpan keunikan kata dalam bentuk set

for _, row in df.iterrows():
    # mengambil kata TF-IDF pada dokumen
    terms_in_doc = row['tf_idf'].keys()

    # menambahkan ke kumpulan semua kata
    all_terms_set.update(terms_in_doc)

# Mengubah set menjadi list terurut
all_terms = sorted(all_terms_set)

all_terms[:10]

['0', '00', '000', '00002', '0004', '000500', '000eos', '002', '003', '005']

In [21]:
# membuat matriks tfidf menggunakan numpy
print("\nMembentuk matriks TF-IDF untuk seluruh dokumen")

doc_ids = df['id'].astype(int).tolist()

doc_vectors = np.array([
    [row['tf_idf'].get(term, 0) for term in all_terms]
    for _, row in tqdm(df.iterrows(), total=len(df))
])

Membentuk matriks TF-IDF untuk seluruh dokumen

100%|██████████| 1502/1502 [00:59<00:00, 25.40it/s]

In [22]:
# membuat tabel tf-idf
print("\nMembuat tabel TF-IDF")

df_tfidf_table = pd.DataFrame(
    doc_vectors.T,                      # transpose agar baris = term, kolom = dokumen
    index=all_terms,                    # index adalah daftar semua term
    columns=[f"d{doc_id}" for doc_id in doc_ids]   # nama kolom: d1, d2, d3, ...
)

df_tfidf_table.index.name = "Term"

Membuat tabel TF-IDF

In [23]:
from IPython.display import display

# Menampilkan sebagian baris dari tabel TF-IDF
display(df_tfidf_table.iloc[10200:10300])

,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,...,d1493,d1494,d1495,d1496,d1497,d1498,d1499,d1500,d1501,d1502
Term,,,,,,,,,,,,,,,,,,,,,
mazzoni,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mbak,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mbaknya,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mbakyu,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mbendhol04,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
melatih,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
melawab,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
melawan,0.0,0.0,0.0,3.554018,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
melayang,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
melayangkan,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
# 1. Pilih kolom 'd1' dari DataFrame
series_d1 = df_tfidf_table['d1']

# 2. Gunakan Boolean Indexing: ambil hanya nilai yang lebih besar dari 0.0
nilai_diatas_nol_d1 = series_d1[series_d1 > 0.0]

# 3. Tampilkan hasilnya
print("--- Bobot TF-IDF (d1) di atas 0.0 ---")
display(nilai_diatas_nol_d1)

--- Bobot TF-IDF (d1) di atas 0.0 ---

Term
0           6.162224
1           1.077423
10          2.297939
11          2.690246
13          3.052539
              ...
usb         6.622071
usia        4.019382
utamanya    4.830312
wide        6.216606
wifi        6.216606
Name: d1, Length: 172, dtype: float64

In [25]:
def preprocess_query(query):
    query = caseFolding(query)
    query = punctuationRemoval(query)
    query = remove_stopwords(query)
    return query

In [26]:
query = "ekonomi indonesia pertumbuhan inflasi"

# Preprocessing query
query = preprocess_query(query)
print("Query setelah preprocessing:", query)

Query setelah preprocessing: ekonomi indonesia pertumbuhan inflasi

In [27]:
q_tf = compute_word_frequency(query)
print("TF Query:", q_tf)

TF Query: {'ekonomi': 1, 'indonesia': 1, 'pertumbuhan': 1, 'inflasi': 1}

In [28]:
q_tfidf = compute_tf_idf(q_tf, idf)
print("TF-IDF Query:", q_tfidf)

TF-IDF Query: {'ekonomi': 3.052538512711659, 'indonesia': 1.38562924636308, 'pertumbuhan': 3.8812311852678283, 'inflasi': 4.2241759363946585}

In [29]:
# Membuat vektor query dengan panjang yang sama seperti vektor dokumen
query_vector = np.array([q_tfidf.get(term, 0) for term in all_terms])

print("Panjang vector query:", len(query_vector))

Panjang vector query: 19399

In [31]:
# membuat fungsi untuk cosine similarity
def cosine_similarity_manual(vec1, vec2):
    dot_product = np.dot(vec1, vec2)          # perkalian titik (Σ Ai * Bi)
    norm_a = np.linalg.norm(vec1)             # panjang vektor A (akar Σ Ai²)
    norm_b = np.linalg.norm(vec2)             # panjang vektor B (akar Σ Bi²)

    # untuk menghindari pembagian dengan 0
    if norm_a == 0 or norm_b == 0:
        return 0

    return dot_product / (norm_a * norm_b)

# Hitung cosine similarity antara query dan setiap dokumen
similarities = []

for i, doc_vec in enumerate(doc_vectors):
    sim = cosine_similarity_manual(query_vector, doc_vec)
    similarities.append((doc_ids[i], sim))

# Urutkan dari similarity tertinggi
ranked_results = sorted(similarities, key=lambda x: x[1], reverse=True)

# Tampilkan 10 dokumen teratas
print("\n=== Hasil Ranked Retrieval (Top 10) ===")
for doc_id, sim in ranked_results[:10]:
    print(f"Doc {doc_id} -> similarity = {sim:.4f}")

=== Hasil Ranked Retrieval (Top 10) ===
Doc 396 -> similarity = 0.4631
Doc 402 -> similarity = 0.4202
Doc 881 -> similarity = 0.3229
Doc 43 -> similarity = 0.3098
Doc 446 -> similarity = 0.2937
Doc 1056 -> similarity = 0.2918
Doc 1285 -> similarity = 0.2677
Doc 871 -> similarity = 0.2178
Doc 414 -> similarity = 0.2154
Doc 502 -> similarity = 0.2094

In [32]:
doc_to_check = 396     # ubah sesuai ID dokumen yang ingin dicek
row = df[df['id'] == doc_to_check]

if row.empty:
    print("ID dokumen tidak ditemukan.")
else:
    print("\n=== Isi Berita (ID:", doc_to_check, ") ===")
    print(row['isi'].iloc[0])

=== Isi Berita (ID: 396 ) ===
REPUBLIKA.CO.ID, JAKARTA -- Bank Indonesia memprediksi laju inflasi pada akhir 2015 akan mencapai level 4,2 persen hingga 4,3 persen secara tahunan meskipun saat ini masih di atas tujuh persen."Kalau kita kihat akhir kuartal I dan II 2015 ini inflasinya di atas tujuh persen, namun akhir tahun akan ada di plus minus satu persen year on year (secara tahunan)," kata Gubernur BI Agus Martowardojo, Rabu (1/7). Inflasi Juni 2015, sebagaimana baru dirilis oleh Badan Pusat Statistik (BPS), tercatat sebesar 0,54 persen (mtm). Tingkat inflasi tahun kalender (Januari-Juni) 2015 sebesar 0,96 persen dan tingkat inflasi tahun ke tahun (Juni 2015 terhadap Juni 2014) sebesar 7,26 persen.Menurut Agus, memang terdapat indikasi penurunan daya beli masyarakat selama enam bulan pertama tahun ini."Pengaruh daya beli agak lemah mungkin ada. Kita lihat, betul-betul ekonomi 2015 ini dijaga di semester kedua," kata Agus.Sementara itu, terkait inflasi Juni, Deputi Gubernur BI Perry Warjiyo menambahkan bahwa kendati inflasi sedikit lebih tinggi dibandingkan bulan sebelumnya, inflasi Juni relatif lebih rendah dibandingkan tahun-tahun sebelumnya."Inflasi Juni ini juga lebih rendah dari perkiraan kami," ujar Perry.Perry memperkirakan, tingkat inflasi sepanjang 2015 secara keseluruhan akan lebih rendah dibandingkan inflasi 2014."Didorong sisi permintaan yang terkendali dan koordinasi yang erat dengan pemerintah, termasuk TPID-TPID, kami optimis akan mampu mengendalikan inflasi 4 plus minus satu persen pada tahun ini dan tahun depan," kata Perry.Ia juga akan terus mencermati perkembangan ekonomi global dan ikut mendorong perbaikan pertumbuhan ekonomi domestik ke depan.